name: LambdaSync
on:
  push:
    branches:
      - main
    paths: 
      - lambda/s3_script.py
      - lambda/s2quest.py
      - classes/ManageS3.py

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build1"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync Lambda
        run: |
          mkdir ./lambda_files 
          cp ./{classes/ManageS3.py,lambda/*} ./lambda_files
          cd ./lambda_files/
          zip -r9 lambda_files.zip . -i  * > /dev/null
          cp ../scripts/s3lambda.sh ./
          sh ./s3lambda.sh

          AWS_REGION="us-east-1"
          aws configure --profile rearc-quest-aws <<-EOF > /dev/null 2>&1
          $AWS_ACCESS_KEY_ID
          $AWS_SECRET_ACCESS_KEY
          $AWS_REGION
          text
          EOF

          aws lambda update-function-code \
          --function-name automate_quest \
          --zip-file fileb://../lambda_files/lambda_files.zip \
          --profile rearc-quest-aws

          aws lambda update-function-code \
          --function-name S4-3 \
          --zip-file fileb://../lambda_files/lambda_files.zip \
          --profile rearc-quest-aws

          aws configure --profile rearc-quest-aws <<-EOF > /dev/null 2>&1
          null
          null
          null
          text
          EOF

          cd ../
          rm -r ./lambda_files
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


