name: LambdaS3
on:
  push:
    branches:
      - main
    # paths: 
    #   - lambda/s3_script.py

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build1"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Terraform Init
        run: |
          sh /home/runner/work/Rearc-Quest/Rearc-Quest/scripts/terrafom_init.sh
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.9 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          pip install -r /home/runner/work/Rearc-Quest/Rearc-Quest/scripts/requirements.txt
          cp /home/runner/work/Rearc-Quest/Rearc-Quest{/classes/ManageS3.py,/lambda/*} $VIRTUAL_ENV/lib/python3.9/*/
          # cp /home/runner/work/Rearc-Quest/Rearc-Quest/lambda/s3_script.py $VIRTUAL_ENV/lib/python3.9/*/
          # cp /home/runner/work/Rearc-Quest/Rearc-Quest/lambda/s2quest.py $VIRTUAL_ENV/lib/python3.9/*/
          cd $VIRTUAL_ENV/lib/*/*/
          zip -r9 lambda_function.zip * 2>&1 |
          sh /home/runner/work/Rearc-Quest/Rearc-Quest/scripts/s3lambda.sh
          rm -r ./s3_script.py
          rm -r ./ManageS3.py
          rm -r ./s2quest.py
          rm -r ./lambda_function.zip
        env:
          AWS_S3_BUCKET_LAMBDA: ${{ secrets.AWS_S3_BUCKET_LAMBDA }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          File_Name: ./lambda_function.zip

      - name: Terraform
        run: |
          sh /home/runner/work/Rearc-Quest/Rearc-Quest/scripts/TF_Script.sh
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          



