name: LambdaS3
on:
  push:
    branches:
      - main
    # paths: 
    #   - s3_script/s3_script.py

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV- uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          ls $VIRTUAL_ENV
          source $VIRTUAL_ENV/bin/activate
          pip install beautifulsoup4
          pip install lxml
          cp /home/runner/work/Rearc-Quest/Rearc-Quest/lambda/s3_script.py $VIRTUAL_ENV/lib/*/*/
          cd $VIRTUAL_ENV/lib/*/*/
          zip -r9 lambda_function.zip *
          ls ./

      
      - name: S3Lambda
        run: |
          chmod +x ./s3lambda.sh
          ./s3lambda.sh
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_LAMBDA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



