name: LambdaSync
on:
  push:
    branches:
      - main
    paths: 
      - lambda/s3_script.py
      - lambda/s2quest.py
      - classes/ManageS3.py

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build1"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Python commands
        run: |
          sh ./scripts/update_lambda_code.sh
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        
      - name: Terraform
        run: |
          sh /home/runner/work/Rearc-Quest/Rearc-Quest/scripts/TF_Script.sh
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          



